### ISSUE TITLE
Visual Loaders Not Updating Previews 

### ISSUE THREAD

**Issue by 0xion0** [CosmicLaca/ComfyUI_Primere_Nodes#12]
I'm having a small issue with the visual loaders not updating the previews after the initial startup.

I did a test with the previews of a few models and when I saw that it worked, I made previews of all my models. However, only the ones that were made at the beginning are the only ones that are visible. The new ones are not.

I'm not sure if I have to do an extra step or clear the cache somewhere.

**Comment by CosmicLaca** [comment]
@0xion0 Hi, if the new image path and name match with model (jpg only), the loaders usually display instead of 'no image' preview immediately (by my tests). If the available previews updated to new, reload browser with shift key (shift + refresh button for cache delete). Try out the new node to save/update preview, when I tested the new preview created and displayed without reloading, but the update needed shift+refresh. The new node is very easy for manual or semi-automatic preview creation.

![pimgsaveas2](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/7955114/0ec3770a-d846-40bb-9a4c-cf219e8bf815)

-     With **image_save_as switch** you can select **Save as preview** mode, what is the 1 click feature to create preview for visual selectors.
-     Wait while the node contains your generated image.
-     Set **preview_target** by your requirements (Checkpoints, Styles, Loras, Lycoris, Embedding and Hypernetworks). This is depending on the node names what using visual modals for selections. You must use these nodes in the workflow if you use 1 click preview saver.
-     Set **target_selection** from the several values of selected preview_target. These values read from whole workflow when the node contains image.
-     Set **preview_save_mode** to overwrite, keep, concat horizontal, concat vertical to your existing preview.
-     Check the last characters on the button between [?]. C mean button push will create new preview, **O** overwrite existing, **K** keep existing and ignore save, **JV** join vertically new image to existing, **JH** join horizontally new image to existing preview.
-     Push the button if no error messages in the upper combos and in the button. Wait for the response dialog and if all right your image saved as modal preview at right format and size.
