### ISSUE TITLE
Embeddings and loras from styles.csv

### ISSUE THREAD

**Issue by drphero** [CosmicLaca/ComfyUI_Primere_Nodes#6]
Firstly I want to say thank you for taking the time to develop all these nodes. I have no idea how to use them yet, but they look very interesting.

> Read original A1111 styles.csv file, handle dynamic prompts and additional networks from the text content of prompts like in A1111, example dynamic styles.csv included

Does this mean that entries in the styles.csv that include loras, such as \<lora:add_detail:0.5\>, can be used? I'm trying to use the tag loader with the prompt cleaner. Is there a way to see if the tag loader is processing all of the loras and their weights?

Also, I've tried the embedding handler and that seems to work, although it does miss some and I'm not sure why. For example, this negative prompt:
_EasyNegative, negative_hand-neg, (multiple views:1.3), BadDream, UnrealisticDream,(window, fireplace, building, modern tent, camping:1.2),_

becomes:
_embedding:EasyNegative, embedding:negative_hand-neg, (multiple views:1.3), embedding:BadDream, UnrealisticDream,(window, fireplace, building, modern tent, camping:1.2),_

As you can see, it missed UnrealisticDream. And sometimes 'embedding' is added twice, like in this result:

_(low quality, worst quality:1.3, monochrome:1.1), (embedding:EasyNegative, embedding:bad-hands-5:0.6, embedding:embedding:bad_prompt_version2:0.8, embedding:verybadimagenegative_v1.3),_

Last question, a1111 supports the use of {prompt} in styles. Should this be removed before using the embedding handler?

**Comment by CosmicLaca** [comment]
Hi, yes the <networks> format tag processed, but the node deleting the original tag, because by my test the result is better if the lora (or other network) loaded to models and clipping, but deleted from the prompt. So you can't see processed network tags in the result prompt, but the test is easy: freeze the seed, and generate images, you must get same results. Then delete lora tag from prompt (no matter the prompt source, use simple prompt input instead of csv, or modify csv and reload the browser) and run again the process, you have to get different result because lora loaded or not loaded. If network tag available in the prompt, you can play with strength too, you will get different results, while the tag deleted from the prompt.

About embedding, the handler insert 'embedding:' before the keyword, when the embedding filename is exactly same (case sensitive), and available in the system. I'm not sure yet but I will test soon, maybe the 'UnrealisticDream' missed because no space after. Try our 'UnrealisticDream, (win......' 

The double embedding is real error, I will figure out why :)

**Comment by drphero** [comment]
Thanks for all the info. I'm curious to see what's happening with the embeddings.

**Comment by drphero** [comment]
@CosmicLaca I think I have figured out what was causing the double 'embedding:'. I have both bad_prompt.pt and bad_prompt_version2.pt in the embeddings folder. When temporarily moving bad_prompt.pt out of the folder, the double 'embedding:' problem stopped. I came up with a quick fix and submitted a pull request.
