### ISSUE TITLE
Not showing preview images

### ISSUE THREAD

**Issue by noidedxyz** [CosmicLaca/ComfyUI_Primere_Nodes#9]
Maybe I've missed something in the readme but not a single preview image works in the visual selector and I don't know why. They all have standard preview images so I'm not really sure why it refuses to visualize them. Thanks, more information on what exactly it's looking for would also help.

**Comment by CosmicLaca** [comment]
@noidedxyz The preview node cannot read downloaded images from the original folder of loras or checkpoints. Available images must be converted to jpg (small size is important to read fast hundreds of images), but must be copied/moved to the right directory of nodepack.

Step 1: Previews can be only .jpg format with .jpg extension. Don't use large files because the modal loading time. The preview height in visual selector modal is only 220px, so don't use upscaled or original large images as preview. Downsize your previews height to 250-300 px, and set jpg image quality to ~50% for faster loading. ACDSee do it automatically at Tools->Batch->Resize menu if you already have large images, if you generate new by Comfy, just set the upscaler under the 1 (0.4 for SD and 0.2 for SDXL is good enough, while set the jpeg quality to ~50-60 in the image saver node).

Step 2: You must mirror (replicate) your original checkpoint folders (not the checkpoint files!) to **ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\front_end\images\checkpoints\** path but only the preview images needed, same name as the checkpoint but with .jpg only extension (instead of .safetensor). Case sensitive filenames. As extra features you can enable/disable preview modal with 'show_modal' switch, and exclude files and paths from modal starts with . (point) character if 'show_hidden' switch is off. Two checkpoint/lora/etc... selector nodes available, one of them have no preview modal, selectors with modal is only under 'visual' submenu.

Step 3: Set the 'show_modal' switch to true

Good example the 'visual style selector' node, where the example prompts already have preview images.

**Comment by CosmicLaca** [comment]
Helper node coming soon, I hope at next Monday. Image preview node but with 'save as...' function. The 'save as preview' mode automatically collect node settings from whole workflow which have visual preview modal, like checkpoint, loras, etc... then just push the Save button, and image will be saved for visual modals at right size and format. You must create your own image for this function, but no need to resize and convert the result, and found the right target path and name for selected models.
![2024-03-16_09-13-17](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/7955114/f908f2a0-c038-47e8-bdc6-52e3571316e3)

**Comment by CosmicLaca** [comment]
Helper node will help to save preview for visual modal selections.
